#!/usr/bin/with-contenv bash

# This service monitors the service for scaling actions and adds the server (if its the leader)

source /common.sh

# First thing's first, we need to get a lock ... only one service needs to probe the peers

exec consul lock -name glusterfs-$PREFIX $PREFIX ./probe_hosts.sh

echo "Failed to get lock???"
